@extends('Layouts.Layout2')

@section('Content')
    <div class="table-wrapper"> 
        <table class="table">
            <tr>
                <th>#</th>
                <th>Vehicle No</th>
                <th>Status</th>
                <th>Price</th>
                <th>Driver</th>
                <th>Consumption</th>
                <th>Refueling</th>
                <th>Balance</th>
            </tr> 
            <tr>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
            </tr>
            <tr>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
            </tr>
            <tr>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
            </tr>
            <tr>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
            </tr>
            <tr>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
            </tr>
            <tr>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
            </tr>
            <tr>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
            </tr>
            <tr>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
                <td>JSFSK@*IWR</td>
            </tr>
        </table>
    </div>
@endsection