@extends('Layouts.Layout2')

@section('Content')
    <div class="table-wrapper"> 
        <table class="table">
            <tr>
                <th>LNO</th>
                <th>Date</th>
                <th>Card No</th>
                <th>Amount</th>
                <th>Year</th>
                <th>Week</th>
                <th>Month</th>
            </tr>
            <tr>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
            </tr>
            <tr>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
            </tr>
            <tr>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
            </tr>
            <tr>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
            </tr>
            <tr>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
            </tr>
            <tr>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
            </tr>
            <tr>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
            </tr>
            <tr>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
            </tr>
            <tr>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
            </tr>
            <tr>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
                <td>TESTSZ</td>
            </tr>
        </table>
    </div>
@endsection