<?php

namespace App\Http\Controllers;

use Codedge\Fpdf\Fpdf\Fpdf;
use Illuminate\Http\Request;

class InspectionReportPdfController extends Controller
{
    protected $fpdf;

    public function __construct()
    {
        $this->fpdf = new Fpdf;
    }

    public function index(Request $request) 
    { 
        $MyInspectionReport = \DB::table('inspection_report')->where('InspectionNumber', $request->InspectionNumber)->first();
        $ExteriorInspection = \DB::table('exterior_inspection')->where('InspectionNumber', $request->InspectionNumber)->first();
        $InteriorInspection = \DB::table('interior_inspection')->where('InspectionNumber', $request->InspectionNumber)->first();
        $FluidLevels = \DB::table('fluid_levels')->where('InspectionNumber', $request->InspectionNumber)->first();
        $MechanicalInspection = \DB::table('mechanical_inspection')->where('InspectionNumber', $request->InspectionNumber)->first();
        $SafetyEquipment = \DB::table('safety_equipment')->where('InspectionNumber', $request->InspectionNumber)->first();

        $this->fpdf->SetFont('Arial', 'B', 15);
        $this->fpdf->SetTitle('Inspection Report - ' . $request->InspectionNumber);
        $this->fpdf->SetTextColor(245, 37, 95);
        $this->fpdf->SetFillColor(227, 232, 243);
        $this->fpdf->AddPage();

        $this->fpdf->SetTextColor(223, 46, 56);
        $this->fpdf->SetFont('Arial', '', 8);
        $this->fpdf->Cell(50, -11, 'Powered By - http://' . $_SERVER['HTTP_HOST']);
        $this->fpdf->SetFont('Arial', 'B', 10); 
        $this->fpdf->Ln(0); 
        $this->fpdf->SetDrawColor(49, 52, 56);
        $this->fpdf->SetFont('Arial', '', 8);  
        $this->fpdf->SetTextColor(78,85,211);
        $this->fpdf->Cell(190, 8,'Depasa Marine International', 0, 0, 'R'); 
        $this->fpdf->SetTextColor(0,0,0);
        
        $this->fpdf->Ln();    
        $this->fpdf->SetFont('Arial', 'B', 15);   
        $this->fpdf->SetTextColor(49, 52, 56);
        $this->fpdf->Cell(190, 9,'VEHICLE INSPECTION REPORT', 0, 0, 'L', 1);  
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', '', 9);   
        $this->fpdf->Ln();   
        $this->fpdf->MultiCell(190, 4,'This report is an essential document that provides comprehensive information about the condition of this vehicle. It helps to identify any issues or potential problems with the vehicle and can be used to verify its condition before purchase or sale. This report is essential to ensure the safety and reliability of the vehicle.'); 
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', 'B', 11);  
        $this->fpdf->Cell(190, 8,'DAILY VEHICLE INSPECTION DETAILS', 'B');  
        $this->fpdf->SetFont('Arial', '', 9);  
        $this->fpdf->Cell(0, 10,' ', 0, 0);    
        $this->fpdf->Ln();   

        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->Cell(120, 5,'Inspection Number:', 0, 0);   
        $this->fpdf->Cell(140, 5,'Vehicle Plate #:', 0, 0);   
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->Cell(80, 8, $request->InspectionNumber, 0, 0);  
        $this->fpdf->Cell(40, 8,' ', 0, 0);   
        $this->fpdf->Cell(70, 8, $MyInspectionReport->VehicleNumber, 0, 0);   
        $this->fpdf->Cell(0, 10,' ', 0, 0);   
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->Cell(120, 5,'Mileage:', 0, 0);   
        $this->fpdf->Cell(140, 5,'Date Inspected:', 0, 0);   
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->Cell(80, 8, $MyInspectionReport->Mileage, 0, 0);  
        $this->fpdf->Cell(40, 8,' ', 0, 0);    
        $this->fpdf->Cell(70, 8, $MyInspectionReport->DateInspected, 0, 0);  
        $this->fpdf->Cell(0, 10,' ', 0, 0);    
        $this->fpdf->Ln();     
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->Cell(120, 5,'Inspected By:', 0, 0);    
        $this->fpdf->Cell(140, 5,'Status:', 0, 0); 
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->Cell(80, 8, $MyInspectionReport->InspectedBy, 0, 0); 
        $this->fpdf->Cell(40, 8,' ', 0, 0);  
        $this->fpdf->Cell(70, 8, $MyInspectionReport->Status, 0, 0);  
        $this->fpdf->Cell(0, 10,' ', 0, 0);   
        $this->fpdf->Ln();     
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->Cell(120, 5,'Assigned Mechanic/Agent:', 0, 0);  
        $this->fpdf->SetFont('Arial', '', 9);   
        $this->fpdf->Ln();   
        $this->fpdf->Cell(80, 8, $MyInspectionReport->Mechanic, 0, 0,); 
  
        $this->fpdf->Cell(0, 10,' ', 0, 0);   
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', 'B', 11);  
        $this->fpdf->Cell(190, 9,'ITEM CHECKLIST', 0, 0, 'L', 1);  
        $this->fpdf->SetTextColor(49, 52, 56); 
        $this->fpdf->SetFont('Arial', '', 9);

        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 10,' ', 0, 0); 
        $this->fpdf->SetTextColor(245, 37, 95);
        $this->fpdf->Cell(20, 10,'BAD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(42, 201, 47);
        $this->fpdf->Cell(20, 10,'GOOD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(71, 128, 213);
        $this->fpdf->Cell(20, 10,'N/A', 0, 0, 'C');  
        $this->fpdf->Ln();      
        $this->fpdf->SetTextColor(49, 52, 56);
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->SetDrawColor(227, 232, 243);
        $this->fpdf->Cell(130, 5, 'Exterior Inspection', 1, 0, 'L', 1); 
        $this->fpdf->SetDrawColor(171, 171, 171); 
        $this->fpdf->SetFont('Arial', '', 9);
        
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check for any damages or scratches on the body', 1, 0);  
        $this->fpdf->Cell(20, 7, $ExteriorInspection->BodyDamages === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->BodyDamages === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->BodyDamages === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Inspect the tires for wear and tear and ensure they are properly inflated', 1, 0); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->TireCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->TireCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->TireCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the windshield and windows for any cracks or chips', 1, 0); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->WindshieldCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->WindshieldCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->WindshieldCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Verify that all lights (headlights, taillights, indicators) are functioning correctly', 1, 0); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->LightsCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->LightsCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->LightsCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Ensure that mirrors are clean and properly adjusted', 1, 0); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->MirrorCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->MirrorCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $ExteriorInspection->MirrorCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 10,' ', 0, 0); 
        $this->fpdf->SetTextColor(245, 37, 95);
        $this->fpdf->Cell(20, 10,'BAD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(42, 201, 47);
        $this->fpdf->Cell(20, 10,'GOOD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(71, 128, 213);
        $this->fpdf->Cell(20, 10,'N/A', 0, 0, 'C');
        $this->fpdf->SetTextColor(49, 52, 56);
    
        $this->fpdf->Ln();     
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->SetDrawColor(227, 232, 243);
        $this->fpdf->Cell(130, 5,'Interior Inspection', 1, 0, 'L', 1); 
        $this->fpdf->SetDrawColor(171, 171, 171);
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->Ln();       
        $this->fpdf->Cell(130, 7,'Check the seat belts for proper functionality and adjust them if necessary', 1, 0); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->SeatBeltsCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->SeatBeltsCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->SeatBeltsCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Inspect the condition of the seats, dashboard, and floor mats', 1, 0); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->SeatsCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->SeatsCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->SeatsCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Test the horn to ensure it is working', 1, 0); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->HornCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->HornCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->HornCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Verify that all controls (AC, heating, audio, etc.) are functioning correctly', 1, 0); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->AllControlsCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->AllControlsCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->AllControlsCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the visibilty by cleaning the windshield and mirrors', 1, 0); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->MirrorVisibility === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->MirrorVisibility === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $InteriorInspection->MirrorVisibility === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 

        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 10,' ', 0, 0); 
        $this->fpdf->SetTextColor(245, 37, 95);
        $this->fpdf->Cell(20, 10,'BAD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(42, 201, 47);
        $this->fpdf->Cell(20, 10,'GOOD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(71, 128, 213);
        $this->fpdf->Cell(20, 10,'N/A', 0, 0, 'C');
        $this->fpdf->SetTextColor(49, 52, 56);
    
        $this->fpdf->Ln();     
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->SetDrawColor(227, 232, 243);
        $this->fpdf->Cell(130, 5,'Fluid Levels', 1, 0, 'L', 1); 
        $this->fpdf->SetDrawColor(171, 171, 171);
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->Ln();       
        $this->fpdf->Cell(130, 7,'Check the engine oil level and add more if needed', 1, 0); 
        $this->fpdf->Cell(20, 7, $FluidLevels->EngineOilCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $FluidLevels->EngineOilCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $FluidLevels->EngineOilCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Verify the coolant level and top up if necessary', 1, 0); 
        $this->fpdf->Cell(20, 7, $FluidLevels->CoolantLevelCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $FluidLevels->CoolantLevelCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $FluidLevels->CoolantLevelCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the brake fluid level and add more if required', 1, 0); 
        $this->fpdf->Cell(20, 7, $FluidLevels->BrakeFluidLevelCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $FluidLevels->BrakeFluidLevelCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $FluidLevels->BrakeFluidLevelCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Ensure the windshield washer fluid is filled', 1, 0); 
        $this->fpdf->Cell(20, 7, $FluidLevels->WindshieldWasherFluidCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $FluidLevels->WindshieldWasherFluidCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $FluidLevels->WindshieldWasherFluidCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the power steering fluid level and add more if needed', 1, 0); 
        $this->fpdf->Cell(20, 7, $FluidLevels->PowerSteeringFluidLevelCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $FluidLevels->PowerSteeringFluidLevelCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $FluidLevels->PowerSteeringFluidLevelCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 

        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 10,' ', 0, 0); 
        $this->fpdf->SetTextColor(245, 37, 95);
        $this->fpdf->Cell(20, 10,'BAD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(42, 201, 47);
        $this->fpdf->Cell(20, 10,'GOOD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(71, 128, 213);
        $this->fpdf->Cell(20, 10,'N/A', 0, 0, 'C');
        $this->fpdf->SetTextColor(49, 52, 56);

        $this->fpdf->Ln();       
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->SetDrawColor(227, 232, 243);
        $this->fpdf->Cell(130, 5,'Mechanical Inspection', 1, 0, 'L', 1); 
        $this->fpdf->SetDrawColor(171, 171, 171); 
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->Ln();       
        $this->fpdf->Cell(130, 7,'Start the engine and listen for any unusual noises or vibrations', 1, 0); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->EngineCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->EngineCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->EngineCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the functionality of the brakes, accelerator, and clutch (if applicable)', 1, 0); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->BrakeCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->BrakeCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->BrakeCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Test the parking brake and ensure it engages and disengages properly', 1, 0); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->BrakeEngagingCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->BrakeEngagingCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->BrakeEngagingCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Inspect the wiper blades for any signs of wear and replace if necessary', 1, 0); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->WiperBladesCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->WiperBladesCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->WiperBladesCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the battery condition and terminals for corrosion', 1, 0); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->BatteryCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->BatteryCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $MechanicalInspection->BatteryCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 

        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 10,' ', 0, 0); 
        $this->fpdf->SetTextColor(245, 37, 95);
        $this->fpdf->Cell(20, 10,'BAD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(42, 201, 47);
        $this->fpdf->Cell(20, 10,'GOOD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(71, 128, 213);
        $this->fpdf->Cell(20, 10,'N/A', 0, 0, 'C');
        $this->fpdf->SetTextColor(49, 52, 56);
  
        $this->fpdf->Ln();     
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->SetDrawColor(227, 232, 243);
        $this->fpdf->Cell(130, 5,'Safety Equipment', 1, 0, 'L', 1); 
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->SetDrawColor(171, 171, 171); 
        $this->fpdf->Ln();       
        $this->fpdf->Cell(130, 7,'Ensure that a spare tire, jack, and lug wrench are present in the vehicle', 1, 0); 
        $this->fpdf->Cell(20, 7, $SafetyEquipment->PresenceOfSpareTire === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $SafetyEquipment->PresenceOfSpareTire === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $SafetyEquipment->PresenceOfSpareTire === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Verify the presence of a first aid kit and a fire extinguisher', 1, 0); 
        $this->fpdf->Cell(20, 7, $SafetyEquipment->PresenceOfFirstAidKit === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $SafetyEquipment->PresenceOfFirstAidKit === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $SafetyEquipment->PresenceOfFirstAidKit === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the functioning of all safety features, such as airbags and seatbelt pretensioners', 1, 0); 
        $this->fpdf->Cell(20, 7, $SafetyEquipment->FunctionalityOfAllSafetyFeatures === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $SafetyEquipment->FunctionalityOfAllSafetyFeatures === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $SafetyEquipment->FunctionalityOfAllSafetyFeatures === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Test the operation of the emergency lights and warning triangle (if available)', 1, 0); 
        $this->fpdf->Cell(20, 7, $SafetyEquipment->EmergencyLightsCondition === 'BAD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $SafetyEquipment->EmergencyLightsCondition === 'GOOD' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, $SafetyEquipment->EmergencyLightsCondition === 'NO_ANSWER' ? '*' : '', 1, 0, 'C'); 
        $this->fpdf->Ln();       
        $this->fpdf->Ln();       

        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->Cell(20, 7, 'Remarks:', 0, 0, 'C'); 
        $this->fpdf->SetFont('Arial', '', 11);
        $this->fpdf->Ln();    
        $this->fpdf->MultiCell(190, 7, $MyInspectionReport->AdditionalNotes ?? 'No remarks for this inspection.', 'B'); 
        
        $this->fpdf->Ln(130);  
        $this->fpdf->Cell(80, 6, '');  
        $this->fpdf->Image('../public/Images/depasa-signature.png', 11, 270, 30, 20);
            
        $this->fpdf->SetTextColor(223, 46, 56);
        $this->fpdf->SetFont('Arial', '', 7);
        $this->fpdf->Cell(50, 6, 'http://' . $_SERVER['HTTP_HOST']);

        $this->fpdf->Output();

        exit;
    }
    
    public function daily_vehicle_inspection_form(Request $request) 
    {  

        $this->fpdf->SetFont('Arial', 'B', 15);
        $this->fpdf->SetTitle('Vehicle Inspection Form');
        $this->fpdf->SetTextColor(245, 37, 95);
        $this->fpdf->SetFillColor(227, 232, 243);
        $this->fpdf->AddPage();

        $this->fpdf->SetTextColor(223, 46, 56);
        $this->fpdf->SetFont('Arial', '', 8);
        $this->fpdf->Cell(50, -11, 'Powered By - http://' . $_SERVER['HTTP_HOST']);
        $this->fpdf->SetFont('Arial', 'B', 10); 
        $this->fpdf->Ln(0); 
        $this->fpdf->SetDrawColor(49, 52, 56);
        $this->fpdf->SetFont('Arial', '', 8);  
        $this->fpdf->SetTextColor(78,85,211);
        $this->fpdf->Cell(190, 8,'Depasa Marine International', 0, 0, 'R'); 
        $this->fpdf->Ln();    
        $this->fpdf->SetFont('Arial', 'B', 15);   
        $this->fpdf->SetTextColor(49, 52, 56);
        $this->fpdf->Cell(190, 9,'VEHICLE INSPECTION FORM', 0, 0, 'L', 1);  
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', '', 9);   
        $this->fpdf->Ln();   
        $this->fpdf->MultiCell(190, 4,'This form is used to assess the condition of a vehicle. It is typically used by mechanics, auto shops, and government agencies to ensure that vehicles are safe and roadworthy. The form typically includes information about the vehicle, such as its plate number, mileage, etc as well as a checklist of items to inspect. These items may include the brakes, tires, steering, suspension, lights, and emissions system. The inspector will mark each item as "pass" or "fail" based on its condition, and may provide additional comments or recommendations.'); 
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', 'B', 11);  
        $this->fpdf->Cell(190, 8,'DAILY VEHICLE INSPECTION CHECKLIST', 'B');  
        $this->fpdf->SetFont('Arial', '', 9);  
        $this->fpdf->Cell(0, 10,' ', 0, 0);    
        $this->fpdf->Ln();   

        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->Cell(120, 5,'Inspection Number:', 0, 0);   
        $this->fpdf->Cell(140, 5,'Vehicle Plate #:', 0, 0);   
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->Cell(80, 8, date('Ymd') . date('his'), 0, 0);  
        $this->fpdf->Cell(40, 8,' ', 0, 0);   
        $this->fpdf->Cell(70, 8, '', 'B');   
        $this->fpdf->Cell(0, 10,' ', 0, 0);   
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->Cell(120, 5,'Mileage:', 0, 0);   
        $this->fpdf->Cell(140, 5,'Date Inspected:', 0, 0);   
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->Cell(80, 8, '', 'B');  
        $this->fpdf->Cell(40, 8,' ', 0, 0);    
        $this->fpdf->Cell(70, 8, '', 'B');  
        $this->fpdf->Cell(0, 10,' ', 'B');    
        $this->fpdf->Ln();     
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->Cell(120, 5,'Inspected By:', 0, 0);    
        $this->fpdf->Cell(140, 5,'Status (GOOD / FAIR / BAD):', 0, 0); 
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->Cell(80, 8, '', 'B'); 
        $this->fpdf->Cell(40, 8,' ', 0, 0);  
        $this->fpdf->Cell(70, 8, '', 'B');  
        $this->fpdf->Cell(0, 10,' ', 0, 0);   
        $this->fpdf->Ln();     
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->Cell(120, 5,'Assigned Mechanic/Agent:', 0, 0);  
        $this->fpdf->SetFont('Arial', '', 9);   
        $this->fpdf->Ln();   
        $this->fpdf->Cell(80, 8, '', 'B'); 
  
        $this->fpdf->Cell(0, 10,' ', 0, 0);   
        $this->fpdf->Ln();   
        $this->fpdf->SetFont('Arial', 'B', 11);  
        $this->fpdf->Cell(190, 9,'ITEM CHECKLIST', 0, 0, 'L', 1);  
        $this->fpdf->SetTextColor(49, 52, 56); 
        $this->fpdf->SetFont('Arial', '', 9);

        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 10,' ', 0, 0); 
        $this->fpdf->SetTextColor(245, 37, 95);
        $this->fpdf->Cell(20, 10,'BAD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(42, 201, 47);
        $this->fpdf->Cell(20, 10,'GOOD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(71, 128, 213);
        $this->fpdf->Cell(20, 10,'N/A', 0, 0, 'C');  
        $this->fpdf->Ln();      
        $this->fpdf->SetTextColor(49, 52, 56);
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->SetDrawColor(227, 232, 243);
        $this->fpdf->Cell(130, 5, 'Exterior Inspection', 1, 0, 'L', 1); 
        $this->fpdf->SetDrawColor(171, 171, 171); 
        $this->fpdf->SetFont('Arial', '', 9);
        
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check for any damages or scratches on the body', 1, 0);  
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Inspect the tires for wear and tear and ensure they are properly inflated', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the windshield and windows for any cracks or chips', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Verify that all lights (headlights, taillights, indicators) are functioning correctly', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Ensure that mirrors are clean and properly adjusted', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 10,' ', 0, 0); 
        $this->fpdf->SetTextColor(245, 37, 95);
        $this->fpdf->Cell(20, 10,'BAD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(42, 201, 47);
        $this->fpdf->Cell(20, 10,'GOOD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(71, 128, 213);
        $this->fpdf->Cell(20, 10,'N/A', 0, 0, 'C');
        $this->fpdf->SetTextColor(49, 52, 56);
    
        $this->fpdf->Ln();     
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->SetDrawColor(227, 232, 243);
        $this->fpdf->Cell(130, 5,'Interior Inspection', 1, 0, 'L', 1); 
        $this->fpdf->SetDrawColor(171, 171, 171);
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->Ln();       
        $this->fpdf->Cell(130, 7,'Check the seat belts for proper functionality and adjust them if necessary', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Inspect the condition of the seats, dashboard, and floor mats', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Test the horn to ensure it is working', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Verify that all controls (AC, heating, audio, etc.) are functioning correctly', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the visibilty by cleaning the windshield and mirrors', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 

        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 10,' ', 0, 0); 
        $this->fpdf->SetTextColor(245, 37, 95);
        $this->fpdf->Cell(20, 10,'BAD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(42, 201, 47);
        $this->fpdf->Cell(20, 10,'GOOD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(71, 128, 213);
        $this->fpdf->Cell(20, 10,'N/A', 0, 0, 'C');
        $this->fpdf->SetTextColor(49, 52, 56);
    
        $this->fpdf->Ln();     
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->SetDrawColor(227, 232, 243);
        $this->fpdf->Cell(130, 5,'Fluid Levels', 1, 0, 'L', 1); 
        $this->fpdf->SetDrawColor(171, 171, 171);
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->Ln();       
        $this->fpdf->Cell(130, 7,'Check the engine oil level and add more if needed', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Verify the coolant level and top up if necessary', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the brake fluid level and add more if required', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Ensure the windshield washer fluid is filled', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the power steering fluid level and add more if needed', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 

        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 10,' ', 0, 0); 
        $this->fpdf->SetTextColor(245, 37, 95);
        $this->fpdf->Cell(20, 10,'BAD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(42, 201, 47);
        $this->fpdf->Cell(20, 10,'GOOD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(71, 128, 213);
        $this->fpdf->Cell(20, 10,'N/A', 0, 0, 'C');
        $this->fpdf->SetTextColor(49, 52, 56);

        $this->fpdf->Ln();       
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->SetDrawColor(227, 232, 243);
        $this->fpdf->Cell(130, 5,'Mechanical Inspection', 1, 0, 'L', 1); 
        $this->fpdf->SetDrawColor(171, 171, 171); 
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->Ln();       
        $this->fpdf->Cell(130, 7,'Start the engine and listen for any unusual noises or vibrations', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the functionality of the brakes, accelerator, and clutch (if applicable)', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Test the parking brake and ensure it engages and disengages properly', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Inspect the wiper blades for any signs of wear and replace if necessary', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the battery condition and terminals for corrosion', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 

        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 10,' ', 0, 0); 
        $this->fpdf->SetTextColor(245, 37, 95);
        $this->fpdf->Cell(20, 10,'BAD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(42, 201, 47);
        $this->fpdf->Cell(20, 10,'GOOD', 0, 0, 'C'); 
        $this->fpdf->SetTextColor(71, 128, 213);
        $this->fpdf->Cell(20, 10,'N/A', 0, 0, 'C');
        $this->fpdf->SetTextColor(49, 52, 56);
  
        $this->fpdf->Ln();     
        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->SetDrawColor(227, 232, 243);
        $this->fpdf->Cell(130, 5,'Safety Equipment', 1, 0, 'L', 1); 
        $this->fpdf->SetFont('Arial', '', 9);
        $this->fpdf->SetDrawColor(171, 171, 171); 
        $this->fpdf->Ln();       
        $this->fpdf->Cell(130, 7,'Ensure that a spare tire, jack, and lug wrench are present in the vehicle', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Verify the presence of a first aid kit and a fire extinguisher', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Check the functioning of all safety features, such as airbags and seatbelt pretensioners', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();      
        $this->fpdf->Cell(130, 7,'Test the operation of the emergency lights and warning triangle (if available)', 1, 0); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Cell(20, 7, '', 1, 0, 'C'); 
        $this->fpdf->Ln();       
        $this->fpdf->Ln();    

        $this->fpdf->SetFont('Arial', 'B', 11);
        $this->fpdf->Cell(20, 7, 'Remarks:', 0, 0, 'C'); 
        $this->fpdf->Ln();    
        $this->fpdf->Cell(190, 7, '', 'B'); 
        $this->fpdf->Ln();     
        $this->fpdf->Cell(190, 7, '', 'B'); 
        $this->fpdf->Ln();    
        $this->fpdf->Cell(190, 7, '', 'B'); 
        $this->fpdf->Ln();    
        $this->fpdf->Cell(190, 7, '', 'B'); 
        $this->fpdf->Ln();    
        $this->fpdf->Cell(190, 7, '', 'B'); 
        $this->fpdf->Ln();    
        $this->fpdf->Cell(190, 7, '', 'B'); 
        $this->fpdf->Ln();    
        $this->fpdf->Cell(190, 7, '', 'B'); 
        $this->fpdf->Ln();    
        $this->fpdf->Cell(190, 7, '', 'B'); 
        $this->fpdf->Ln(70);    
         
        $this->fpdf->Cell(80, 6, '');  
        $this->fpdf->Image('../public/Images/depasa-signature.png', 11, 250, 30, 20);
            
        $this->fpdf->SetTextColor(223, 46, 56);
        $this->fpdf->SetFont('Arial', '', 7);
        $this->fpdf->Cell(30, 6, $_SERVER['HTTP_HOST']);


        $this->fpdf->Output();

        exit;
    }
}
